#!/bin/bash
set -eu

bindir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$bindir"

if git rev-parse --git-dir > /dev/null 2>&1; then
  # we are in git repository
  ID=$( git rev-parse HEAD )
  git diff --quiet || ID+="_(dirty)"
else
  # this is not a git repository
  ID='-'
fi

echo "$ID"
