#!/bin/bash
set -eu

bindir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$bindir"

if git rev-parse --git-dir > /dev/null 2>&1; then
  # we are in git repository
  ID=$( git rev-parse HEAD )
  git diff --quiet || ID+="_(dirty)"
else
  # this is not a git repository
  ID='-'
fi

REVSION=0
if [ -e apps/xbufr/version.h ]; then
  REVSION=$( grep REVISION apps/xbufr/version.h | cut -d' ' -f3- )
fi

if [ "${ID}" != "${REVSION}" ]; then
  sed s:_GIT_REVISION_:${ID}: apps/xbufr/version.h.in > apps/xbufr/version.h
  echo "New git revision $ID"
else
  echo "Same git revision $ID"
fi
