name: Release macOS

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build qt
      run: |
        brew install md5sha1sum ninja
        mkdir qt610 && cd qt610
        ../scripts/build_qt.sh

    - name: Build
      run: |
        VERSION=$(cat VERSION)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/qt610/qt-6.1.0 -DCMAKE_INSTALL_PREFIX=install
        make install
        mv xbufr.dmg  xbufr-macos-${VERSION}.dmg

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        files: |
          ./build/xbufr*.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
