
name: Release macOS

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update brew packages
      run: |
        brew install qt

    - name: Build
      run: |
        echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=install
        make install VERBOSE=1

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        files: |
          ./build/xbufr.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
